// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqS0qmZSbOjkEx6D3xeymUPWJ84LXa1zs',
    appId: '1:793505984722:web:831b491820d78c318c3d0b',
    messagingSenderId: '793505984722',
    projectId: 'instagram-clone-9db93',
    authDomain: 'instagram-clone-9db93.firebaseapp.com',
    storageBucket: 'instagram-clone-9db93.appspot.com',
    measurementId: 'G-0VBQSHQDPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfgPPsn-NQUOGeRIEj-YK-3cTNWBrIpP4',
    appId: '1:793505984722:android:d5b74d791255c0918c3d0b',
    messagingSenderId: '793505984722',
    projectId: 'instagram-clone-9db93',
    storageBucket: 'instagram-clone-9db93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL0xvZ3v8q6TDkK2SN295yiV4QKbgBRPM',
    appId: '1:793505984722:ios:9fd976e0094cadc98c3d0b',
    messagingSenderId: '793505984722',
    projectId: 'instagram-clone-9db93',
    storageBucket: 'instagram-clone-9db93.appspot.com',
    iosBundleId: 'com.example.instagramApp',
  );
}
